version: "3.8"
services:
  db:
    container_name: "aoba_db"
    image: postgres:latest
    restart: "always"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=Aoba
    volumes:
      - db:/var/lib/postgresql/data
  api:
    container_name: "aoba_api"
    build:
      context: ./
    restart: always
    depends_on:
      - db
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://aoba_db:5432/Aoba
      - SPRING_JPA_GENERATE_DDL=true
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
volumes:
  db: